import "server-only";
import { google } from "googleapis";

const EXPENSES = "CRM Expenses";
const PAYMENTS = "CRM Payments";
export const paymentModes = ["Bank transfer", "UPI", "Cash", "Cheque", "Card", "Other"] as const;
export const paymentTypes = ["Invoice payment", "Advance received", "Refund"] as const;
export type PaymentMode = typeof paymentModes[number];
export type PaymentType = typeof paymentTypes[number];
export type Expense = { createdAt: string; reference: string; expenseDate: string; category: string; vendor: string; project: string; amount: number; gstInvoiceAvailable: boolean; notes: string };
export type Payment = { createdAt: string; reference: string; receiptDate: string; invoiceReference: string; customer: string; amount: number; mode: PaymentMode; type: PaymentType; transactionReference: string; notes: string };

function sheets() { const auth=new google.auth.GoogleAuth({ credentials:{ project_id:process.env.GOOGLE_PROJECT_ID,client_email:process.env.GOOGLE_CLIENT_EMAIL,private_key:process.env.GOOGLE_PRIVATE_KEY?.replace(/\\n/g,"\n") },scopes:["https://www.googleapis.com/auth/spreadsheets"]}); return google.sheets({version:"v4",auth}); }
async function ensureSheet(client:ReturnType<typeof sheets>,name:string,headers:string[]) { const book=await client.spreadsheets.get({spreadsheetId:process.env.GOOGLE_SHEET_ID!,fields:"sheets.properties"}); if(!book.data.sheets?.some(s=>s.properties?.title===name)){await client.spreadsheets.batchUpdate({spreadsheetId:process.env.GOOGLE_SHEET_ID!,requestBody:{requests:[{addSheet:{properties:{title:name}}}]}});await client.spreadsheets.values.update({spreadsheetId:process.env.GOOGLE_SHEET_ID!,range:"'"+name+"'!A1:"+String.fromCharCode(64+headers.length)+"1",valueInputOption:"USER_ENTERED",requestBody:{values:[headers]}});} }
async function ensure(){if(!process.env.GOOGLE_SHEET_ID) throw new Error("GOOGLE_SHEET_ID is missing."); const client=sheets();await ensureSheet(client,EXPENSES,["Created at","Expense no.","Expense date","Category","Vendor","Project / cost centre","Amount","GST invoice available","Notes"]);await ensureSheet(client,PAYMENTS,["Created at","Receipt no.","Receipt date","Invoice reference","Customer","Amount","Mode","Receipt type","Transaction reference","Notes"]);return client;}
export async function getFinanceData():Promise<{expenses:Expense[];payments:Payment[]}>{if(!process.env.GOOGLE_SHEET_ID||!process.env.GOOGLE_CLIENT_EMAIL||!process.env.GOOGLE_PRIVATE_KEY)return{expenses:[],payments:[]};try{const client=sheets();const book=await client.spreadsheets.get({spreadsheetId:process.env.GOOGLE_SHEET_ID,fields:"sheets.properties"});const has=(name:string)=>Boolean(book.data.sheets?.some(s=>s.properties?.title===name));const [expenseRes,paymentRes]=await Promise.all([has(EXPENSES)?client.spreadsheets.values.get({spreadsheetId:process.env.GOOGLE_SHEET_ID,range:"'"+EXPENSES+"'!A2:I"}):Promise.resolve({data:{values:[] as string[][]}}),has(PAYMENTS)?client.spreadsheets.values.get({spreadsheetId:process.env.GOOGLE_SHEET_ID,range:"'"+PAYMENTS+"'!A2:J"}):Promise.resolve({data:{values:[] as string[][]}})]);return{expenses:(expenseRes.data.values??[]).map(r=>({createdAt:String(r[0]??""),reference:String(r[1]??""),expenseDate:String(r[2]??""),category:String(r[3]??""),vendor:String(r[4]??""),project:String(r[5]??""),amount:Number(r[6]||0),gstInvoiceAvailable:String(r[7]??"").toLowerCase()==="yes",notes:String(r[8]??"")})).reverse(),payments:(paymentRes.data.values??[]).map(r=>({createdAt:String(r[0]??""),reference:String(r[1]??""),receiptDate:String(r[2]??""),invoiceReference:String(r[3]??""),customer:String(r[4]??""),amount:Number(r[5]||0),mode:paymentModes.includes(String(r[6]??"") as PaymentMode)?String(r[6]) as PaymentMode:"Bank transfer",type:paymentTypes.includes(String(r[7]??"") as PaymentType)?String(r[7]) as PaymentType:"Invoice payment",transactionReference:String(r[8]??""),notes:String(r[9]??"")})).reverse()};}catch{return{expenses:[],payments:[]};}}
async function nextReference(client:ReturnType<typeof sheets>,sheet:string,prefix:string){const data=await client.spreadsheets.values.get({spreadsheetId:process.env.GOOGLE_SHEET_ID!,range:"'"+sheet+"'!A2:B"});const year=new Date().getFullYear();return prefix+"-"+year+"-"+String((data.data.values??[]).filter(r=>String(r[0]??"").startsWith(String(year))).length+1).padStart(4,"0");}
export async function createExpense(input:Omit<Expense,"createdAt"|"reference">){const client=await ensure();const reference=await nextReference(client,EXPENSES,"EXP");await client.spreadsheets.values.append({spreadsheetId:process.env.GOOGLE_SHEET_ID!,range:"'"+EXPENSES+"'!A:I",valueInputOption:"USER_ENTERED",requestBody:{values:[[new Date().toISOString(),reference,input.expenseDate,input.category,input.vendor,input.project,input.amount,input.gstInvoiceAvailable?"Yes":"No",input.notes]]}});return{reference};}
export async function createPayment(input:Omit<Payment,"createdAt"|"reference">){const client=await ensure();const reference=await nextReference(client,PAYMENTS,"RCT");await client.spreadsheets.values.append({spreadsheetId:process.env.GOOGLE_SHEET_ID!,range:"'"+PAYMENTS+"'!A:J",valueInputOption:"USER_ENTERED",requestBody:{values:[[new Date().toISOString(),reference,input.receiptDate,input.invoiceReference,input.customer,input.amount,input.mode,input.type,input.transactionReference,input.notes]]}});return{reference};}