import "server-only";
import { google } from "googleapis";

const ATTENDANCE="CRM Attendance", LEAVES="CRM Leave Requests", PAYROLL="CRM Payroll Runs";
export const attendanceStatuses=["Present","Absent","Half day","Leave","Work from home"] as const;
export const leaveStatuses=["Pending","Approved","Rejected","Cancelled"] as const;
export const payrollStatuses=["Draft","Reviewed","Paid"] as const;
export type AttendanceStatus=typeof attendanceStatuses[number]; export type LeaveStatus=typeof leaveStatuses[number]; export type PayrollStatus=typeof payrollStatuses[number];
export type Attendance={createdAt:string;reference:string;attendanceDate:string;employee:string;status:AttendanceStatus;notes:string};
export type LeaveRequest={createdAt:string;reference:string;employee:string;leaveType:string;fromDate:string;toDate:string;reason:string;status:LeaveStatus;notes:string};
export type PayrollRun={createdAt:string;reference:string;month:string;employee:string;gross:number;allowances:number;deductions:number;net:number;status:PayrollStatus;notes:string};
function sheets(){const auth=new google.auth.GoogleAuth({credentials:{project_id:process.env.GOOGLE_PROJECT_ID,client_email:process.env.GOOGLE_CLIENT_EMAIL,private_key:process.env.GOOGLE_PRIVATE_KEY?.replace(/\\n/g,"\n")},scopes:["https://www.googleapis.com/auth/spreadsheets"]});return google.sheets({version:"v4",auth});}
async function ensureSheet(client:ReturnType<typeof sheets>,name:string,headers:string[]){const book=await client.spreadsheets.get({spreadsheetId:process.env.GOOGLE_SHEET_ID!,fields:"sheets.properties"});if(!book.data.sheets?.some(s=>s.properties?.title===name)){await client.spreadsheets.batchUpdate({spreadsheetId:process.env.GOOGLE_SHEET_ID!,requestBody:{requests:[{addSheet:{properties:{title:name}}}]}});await client.spreadsheets.values.update({spreadsheetId:process.env.GOOGLE_SHEET_ID!,range:"'"+name+"'!A1:"+String.fromCharCode(64+headers.length)+"1",valueInputOption:"USER_ENTERED",requestBody:{values:[headers]}});}}
async function ensure(){if(!process.env.GOOGLE_SHEET_ID)throw new Error("GOOGLE_SHEET_ID is missing.");const client=sheets();await ensureSheet(client,ATTENDANCE,["Created at","Attendance ID","Date","Employee","Status","Notes"]);await ensureSheet(client,LEAVES,["Created at","Leave ID","Employee","Leave type","From date","To date","Reason","Status","Notes"]);await ensureSheet(client,PAYROLL,["Created at","Payroll ID","Month","Employee","Gross input","Allowances","Manual deductions","Net payout draft","Status","Notes"]);return client;}
export async function getPeopleOpsData():Promise<{attendance:Attendance[];leaves:LeaveRequest[];payroll:PayrollRun[]}>{if(!process.env.GOOGLE_SHEET_ID||!process.env.GOOGLE_CLIENT_EMAIL||!process.env.GOOGLE_PRIVATE_KEY)return{attendance:[],leaves:[],payroll:[]};try{const client=sheets();const book=await client.spreadsheets.get({spreadsheetId:process.env.GOOGLE_SHEET_ID,fields:"sheets.properties"});const has=(n:string)=>Boolean(book.data.sheets?.some(s=>s.properties?.title===n));const [a,l,p]=await Promise.all([has(ATTENDANCE)?client.spreadsheets.values.get({spreadsheetId:process.env.GOOGLE_SHEET_ID,range:"'"+ATTENDANCE+"'!A2:F"}):Promise.resolve({data:{values:[] as string[][]}}),has(LEAVES)?client.spreadsheets.values.get({spreadsheetId:process.env.GOOGLE_SHEET_ID,range:"'"+LEAVES+"'!A2:I"}):Promise.resolve({data:{values:[] as string[][]}}),has(PAYROLL)?client.spreadsheets.values.get({spreadsheetId:process.env.GOOGLE_SHEET_ID,range:"'"+PAYROLL+"'!A2:J"}):Promise.resolve({data:{values:[] as string[][]}})]);return{attendance:(a.data.values??[]).map(r=>({createdAt:String(r[0]??""),reference:String(r[1]??""),attendanceDate:String(r[2]??""),employee:String(r[3]??""),status:attendanceStatuses.includes(String(r[4]??"")as AttendanceStatus)?String(r[4])as AttendanceStatus:"Present",notes:String(r[5]??"")})).reverse(),leaves:(l.data.values??[]).map(r=>({createdAt:String(r[0]??""),reference:String(r[1]??""),employee:String(r[2]??""),leaveType:String(r[3]??""),fromDate:String(r[4]??""),toDate:String(r[5]??""),reason:String(r[6]??""),status:leaveStatuses.includes(String(r[7]??"")as LeaveStatus)?String(r[7])as LeaveStatus:"Pending",notes:String(r[8]??"")})).reverse(),payroll:(p.data.values??[]).map(r=>({createdAt:String(r[0]??""),reference:String(r[1]??""),month:String(r[2]??""),employee:String(r[3]??""),gross:Number(r[4]||0),allowances:Number(r[5]||0),deductions:Number(r[6]||0),net:Number(r[7]||0),status:payrollStatuses.includes(String(r[8]??"")as PayrollStatus)?String(r[8])as PayrollStatus:"Draft",notes:String(r[9]??"")})).reverse()};}catch{return{attendance:[],leaves:[],payroll:[]};}}
async function next(client:ReturnType<typeof sheets>,sheet:string,prefix:string){const data=await client.spreadsheets.values.get({spreadsheetId:process.env.GOOGLE_SHEET_ID!,range:"'"+sheet+"'!A2:B"});const y=new Date().getFullYear();return prefix+"-"+y+"-"+String((data.data.values??[]).filter(r=>String(r[0]??"").startsWith(String(y))).length+1).padStart(4,"0");}
export async function markAttendance(input:Omit<Attendance,"createdAt"|"reference">){const client=await ensure();const reference=await next(client,ATTENDANCE,"ATT");await client.spreadsheets.values.append({spreadsheetId:process.env.GOOGLE_SHEET_ID!,range:"'"+ATTENDANCE+"'!A:F",valueInputOption:"USER_ENTERED",requestBody:{values:[[new Date().toISOString(),reference,input.attendanceDate,input.employee,input.status,input.notes]]}});return{reference};}
export async function createLeave(input:Omit<LeaveRequest,"createdAt"|"reference">){const client=await ensure();const reference=await next(client,LEAVES,"LEV");await client.spreadsheets.values.append({spreadsheetId:process.env.GOOGLE_SHEET_ID!,range:"'"+LEAVES+"'!A:I",valueInputOption:"USER_ENTERED",requestBody:{values:[[new Date().toISOString(),reference,input.employee,input.leaveType,input.fromDate,input.toDate,input.reason,input.status,input.notes]]}});return{reference};}
export async function createPayroll(input:Omit<PayrollRun,"createdAt"|"reference"|"net">){const client=await ensure();const reference=await next(client,PAYROLL,"PAY");const net=Math.max(0,Math.round((input.gross+input.allowances-input.deductions)*100)/100);await client.spreadsheets.values.append({spreadsheetId:process.env.GOOGLE_SHEET_ID!,range:"'"+PAYROLL+"'!A:J",valueInputOption:"USER_ENTERED",requestBody:{values:[[new Date().toISOString(),reference,input.month,input.employee,input.gross,input.allowances,input.deductions,net,input.status,input.notes]]}});return{reference,net};}