import "server-only";
import { google } from "googleapis";
const SHEET="CRM Approvals";
export const approvalTypes=["Purchase","Work Order","Tender","Expense","Payroll","Other"] as const;
export const approvalStatuses=["Pending","Approved","Rejected","Changes requested"] as const;
export type ApprovalType=typeof approvalTypes[number]; export type ApprovalStatus=typeof approvalStatuses[number];
export type Approval={row:number;createdAt:string;reference:string;type:ApprovalType;title:string;relatedReference:string;amount:number;requestedBy:string;dueDate:string;status:ApprovalStatus;decisionNotes:string;decidedAt:string};
function sheets(){const auth=new google.auth.GoogleAuth({credentials:{project_id:process.env.GOOGLE_PROJECT_ID,client_email:process.env.GOOGLE_CLIENT_EMAIL,private_key:process.env.GOOGLE_PRIVATE_KEY?.replace(/\\n/g,"\n")},scopes:["https://www.googleapis.com/auth/spreadsheets"]});return google.sheets({version:"v4",auth});}
async function ensure(){if(!process.env.GOOGLE_SHEET_ID)throw new Error("GOOGLE_SHEET_ID is missing.");const client=sheets();const book=await client.spreadsheets.get({spreadsheetId:process.env.GOOGLE_SHEET_ID,fields:"sheets.properties"});if(!book.data.sheets?.some(s=>s.properties?.title===SHEET)){await client.spreadsheets.batchUpdate({spreadsheetId:process.env.GOOGLE_SHEET_ID,requestBody:{requests:[{addSheet:{properties:{title:SHEET}}}]}});await client.spreadsheets.values.update({spreadsheetId:process.env.GOOGLE_SHEET_ID,range:"'"+SHEET+"'!A1:L1",valueInputOption:"USER_ENTERED",requestBody:{values:[["Created at","Approval ID","Type","Title","Related reference","Amount","Requested by","Due date","Status","Decision notes","Decided at","Internal notes"]]}});}return client;}
export async function getApprovals():Promise<Approval[]>{if(!process.env.GOOGLE_SHEET_ID||!process.env.GOOGLE_CLIENT_EMAIL||!process.env.GOOGLE_PRIVATE_KEY)return[];try{const client=sheets();const book=await client.spreadsheets.get({spreadsheetId:process.env.GOOGLE_SHEET_ID,fields:"sheets.properties"});if(!book.data.sheets?.some(s=>s.properties?.title===SHEET))return[];const data=await client.spreadsheets.values.get({spreadsheetId:process.env.GOOGLE_SHEET_ID,range:"'"+SHEET+"'!A2:L"});return(data.data.values??[]).map((r,index)=>({row:index+2,createdAt:String(r[0]??""),reference:String(r[1]??""),type:approvalTypes.includes(String(r[2]??"")as ApprovalType)?String(r[2])as ApprovalType:"Other",title:String(r[3]??""),relatedReference:String(r[4]??""),amount:Number(r[5]||0),requestedBy:String(r[6]??""),dueDate:String(r[7]??""),status:approvalStatuses.includes(String(r[8]??"")as ApprovalStatus)?String(r[8])as ApprovalStatus:"Pending",decisionNotes:String(r[9]??""),decidedAt:String(r[10]??"")})).reverse();}catch{return[];}}
export async function createApproval(input:Omit<Approval,"row"|"createdAt"|"reference"|"status"|"decisionNotes"|"decidedAt"> & {notes:string}){const client=await ensure();const data=await client.spreadsheets.values.get({spreadsheetId:process.env.GOOGLE_SHEET_ID!,range:"'"+SHEET+"'!A2:B"});const y=new Date().getFullYear();const reference="APR-"+y+"-"+String((data.data.values??[]).filter(r=>String(r[0]??"").startsWith(String(y))).length+1).padStart(4,"0");await client.spreadsheets.values.append({spreadsheetId:process.env.GOOGLE_SHEET_ID!,range:"'"+SHEET+"'!A:L",valueInputOption:"USER_ENTERED",requestBody:{values:[[new Date().toISOString(),reference,input.type,input.title,input.relatedReference,input.amount,input.requestedBy,input.dueDate,"Pending","","",input.notes]]}});return{reference};}
export async function decideApproval(row:number,status:ApprovalStatus,decisionNotes:string){if(!Number.isInteger(row)||row<2||status==="Pending")throw new Error("Invalid approval decision.");const client=await ensure();await client.spreadsheets.values.update({spreadsheetId:process.env.GOOGLE_SHEET_ID!,range:"'"+SHEET+"'!I"+row+":K"+row,valueInputOption:"USER_ENTERED",requestBody:{values:[[status,decisionNotes,new Date().toISOString()]]}});}