"use client";
import { useState } from "react";
export function CreditNoteForm({ invoices, sellerStateCode }: { invoices: Array<{ reference: string; customer: string }>; sellerStateCode: string }) {
  const [originalInvoice, setOriginalInvoice] = useState(invoices[0]?.reference || "");
  const [customer, setCustomer] = useState(invoices[0]?.customer || "");
  const [reason, setReason] = useState("");
  const [placeOfSupplyCode, setPlace] = useState(sellerStateCode);
  const [taxableValue, setTaxable] = useState(0);
  const [taxRate, setTaxRate] = useState(18);
  const [status, setStatus] = useState("");
  async function save() { const response = await fetch("/api/admin/credit-notes", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ originalInvoice, customer, reason, placeOfSupplyCode, taxableValue, taxRate }) }); const data = await response.json().catch(() => null) as { number?: string; error?: string } | null; setStatus(response.ok ? "Credit note saved: " + data?.number : data?.error || "Could not save credit note."); }
  return <section className="mt-6 rounded-xl border border-slate-700 bg-slate-900/70 p-6"><h2 className="text-xl font-bold">Create credit note</h2><p className="mt-1 text-sm text-slate-400">Always select the original invoice and add the reason before saving.</p><div className="mt-5 grid gap-4 md:grid-cols-2"><label>Original invoice<select value={originalInvoice} onChange={e => { setOriginalInvoice(e.target.value); const invoice = invoices.find(item => item.reference === e.target.value); if (invoice) setCustomer(invoice.customer); }} className="mt-2 w-full rounded border border-slate-600 bg-slate-950 p-3">{invoices.length ? invoices.map(invoice => <option key={invoice.reference} value={invoice.reference}>{invoice.reference} — {invoice.customer}</option>) : <option value="">No invoices available</option>}</select></label><label>Customer<input value={customer} onChange={e => setCustomer(e.target.value)} className="mt-2 w-full rounded border border-slate-600 bg-slate-950 p-3" /></label><label>Reason<input value={reason} onChange={e => setReason(e.target.value)} placeholder="Return, price reduction, correction…" className="mt-2 w-full rounded border border-slate-600 bg-slate-950 p-3" /></label><label>Place of Supply code<input value={placeOfSupplyCode} onChange={e => setPlace(e.target.value)} className="mt-2 w-full rounded border border-slate-600 bg-slate-950 p-3" /></label><label>Taxable value<input type="number" min="0" value={taxableValue} onChange={e => setTaxable(Math.max(0, Number(e.target.value) || 0))} className="mt-2 w-full rounded border border-slate-600 bg-slate-950 p-3" /></label><label>GST rate<input type="number" min="0" max="100" value={taxRate} onChange={e => setTaxRate(Math.max(0, Number(e.target.value) || 0))} className="mt-2 w-full rounded border border-slate-600 bg-slate-950 p-3" /></label></div><button type="button" disabled={!invoices.length} onClick={save} className="mt-5 rounded-lg bg-cyan-600 px-5 py-3 font-bold disabled:opacity-60">Save credit note</button>{status && <p className="mt-3 text-sm text-cyan-200">{status}</p>}</section>;
}
