"use client";
import { useRouter } from "next/navigation";
import { useState } from "react";

const purchaseStatuses = ["Requested", "Approved", "Ordered", "Received", "Cancelled"] as const;
const assetStatuses = ["In stock", "Assigned", "Under repair", "Disposed"] as const;
type Vendor={code:string;name:string;category:string;contact:string;email:string;phone:string;gstin:string}; type Purchase={reference:string;vendor:string;item:string;project:string;quantity:number;total:number;status:string;expectedDate:string}; type Asset={assetId:string;name:string;serialNo:string;assignedTo:string;warrantyUntil:string;status:string}; type Project={name:string}; type WorkOrder={reference:string;projectName:string}; type Employee={name:string};

export function ProcurementWorkspace({vendors,purchases,assets,projects,workOrders,employees}:{vendors:Vendor[];purchases:Purchase[];assets:Asset[];projects:Project[];workOrders:WorkOrder[];employees:Employee[]}) {
  const router=useRouter(); const today=new Date().toISOString().slice(0,10); const [message,setMessage]=useState("");
  const [vendorName,setVendorName]=useState(""); const [vendorCategory,setVendorCategory]=useState("Hardware / IT"); const [contact,setContact]=useState(""); const [email,setEmail]=useState(""); const [phone,setPhone]=useState(""); const [gstin,setGstin]=useState("");
  const [purchaseVendor,setPurchaseVendor]=useState(""); const [item,setItem]=useState(""); const [purchaseCategory,setPurchaseCategory]=useState("Hardware"); const [project,setProject]=useState(""); const [quantity,setQuantity]=useState(1); const [unitCost,setUnitCost]=useState(0); const [purchaseStatus,setPurchaseStatus]=useState<typeof purchaseStatuses[number]>("Requested"); const [expectedDate,setExpectedDate]=useState(today);
  const [assetName,setAssetName]=useState(""); const [assetCategory,setAssetCategory]=useState("Hardware"); const [serialNo,setSerialNo]=useState(""); const [purchaseRef,setPurchaseRef]=useState(""); const [location,setLocation]=useState("Office"); const [assignedTo,setAssignedTo]=useState(""); const [warrantyUntil,setWarrantyUntil]=useState(""); const [assetStatus,setAssetStatus]=useState<typeof assetStatuses[number]>("In stock");
  async function save(payload:Record<string,unknown>) { setMessage("Saving…"); const response=await fetch("/api/admin/procurement",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}); const data=await response.json().catch(()=>null) as {error?:string;reference?:string}|null; setMessage(response.ok ? "Saved: "+data?.reference : data?.error || "Could not save record."); if(response.ok) router.refresh(); }
  return <main className="mx-auto max-w-7xl p-8 text-slate-100"><p className="text-xs font-bold tracking-[.15em] text-cyan-300">PROCUREMENT & ASSETS</p><h1 className="mt-2 text-3xl font-black">Vendors, purchases & assets</h1><p className="mt-3 max-w-3xl text-slate-400">Track suppliers, purchase requests and business equipment used for projects, field service and internal work.</p>
    <section className="mt-6 rounded-xl border border-amber-500/40 bg-amber-950/30 p-5 text-sm text-amber-100"><strong>Control point:</strong> Record a purchase here before payment where possible. Supplier invoices, tax credits and payment proof must still be reviewed in Finance/GST before accounting action.</section>
    <div className="mt-6 grid gap-6 xl:grid-cols-3">
      <section className="rounded-xl border border-slate-700 bg-slate-900/70 p-5"><h2 className="text-xl font-bold">Add vendor</h2><div className="mt-4 space-y-3"><input value={vendorName} onChange={e=>setVendorName(e.target.value)} placeholder="Vendor name *" className="w-full rounded border border-slate-600 bg-slate-950 p-3"/><input value={vendorCategory} onChange={e=>setVendorCategory(e.target.value)} placeholder="Category" className="w-full rounded border border-slate-600 bg-slate-950 p-3"/><input value={contact} onChange={e=>setContact(e.target.value)} placeholder="Contact person" className="w-full rounded border border-slate-600 bg-slate-950 p-3"/><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email" className="w-full rounded border border-slate-600 bg-slate-950 p-3"/><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="Phone" className="w-full rounded border border-slate-600 bg-slate-950 p-3"/><input value={gstin} onChange={e=>setGstin(e.target.value.toUpperCase())} placeholder="GSTIN (if applicable)" className="w-full rounded border border-slate-600 bg-slate-950 p-3"/><button onClick={()=>save({kind:"vendor",name:vendorName,category:vendorCategory,contact,email,phone,gstin,notes:""})} className="w-full rounded bg-cyan-600 p-3 font-bold">Save vendor</button></div></section>
      <section className="rounded-xl border border-slate-700 bg-slate-900/70 p-5"><h2 className="text-xl font-bold">Create purchase</h2><div className="mt-4 space-y-3"><select value={purchaseVendor} onChange={e=>setPurchaseVendor(e.target.value)} className="w-full rounded border border-slate-600 bg-slate-950 p-3"><option value="">Vendor not selected</option>{vendors.map(v=><option key={v.code} value={v.name}>{v.name}</option>)}</select><input value={item} onChange={e=>setItem(e.target.value)} placeholder="Item / licence / material *" className="w-full rounded border border-slate-600 bg-slate-950 p-3"/><input value={purchaseCategory} onChange={e=>setPurchaseCategory(e.target.value)} placeholder="Category" className="w-full rounded border border-slate-600 bg-slate-950 p-3"/><select value={project} onChange={e=>setProject(e.target.value)} className="w-full rounded border border-slate-600 bg-slate-950 p-3"><option value="">Internal / not linked</option>{workOrders.map(w=><option key={w.reference} value={w.reference}>{w.reference} — {w.projectName}</option>)}{projects.map(p=><option key={p.name} value={p.name}>{p.name}</option>)}</select><div className="grid grid-cols-2 gap-3"><input type="number" min="1" value={quantity} onChange={e=>setQuantity(Math.max(1,Number(e.target.value)||1))} placeholder="Qty" className="rounded border border-slate-600 bg-slate-950 p-3"/><input type="number" min="0" value={unitCost} onChange={e=>setUnitCost(Math.max(0,Number(e.target.value)||0))} placeholder="Unit cost" className="rounded border border-slate-600 bg-slate-950 p-3"/></div><select value={purchaseStatus} onChange={e=>setPurchaseStatus(e.target.value as typeof purchaseStatus)} className="w-full rounded border border-slate-600 bg-slate-950 p-3">{purchaseStatuses.map(s=><option key={s}>{s}</option>)}</select><input type="date" value={expectedDate} onChange={e=>setExpectedDate(e.target.value)} className="w-full rounded border border-slate-600 bg-slate-950 p-3"/><button onClick={()=>save({kind:"purchase",vendor:purchaseVendor,item,category:purchaseCategory,project,quantity,unitCost,status:purchaseStatus,expectedDate,notes:""})} className="w-full rounded bg-cyan-600 p-3 font-bold">Save purchase</button></div></section>
      <section className="rounded-xl border border-slate-700 bg-slate-900/70 p-5"><h2 className="text-xl font-bold">Register asset</h2><div className="mt-4 space-y-3"><input value={assetName} onChange={e=>setAssetName(e.target.value)} placeholder="Asset name *" className="w-full rounded border border-slate-600 bg-slate-950 p-3"/><input value={assetCategory} onChange={e=>setAssetCategory(e.target.value)} placeholder="Category" className="w-full rounded border border-slate-600 bg-slate-950 p-3"/><input value={serialNo} onChange={e=>setSerialNo(e.target.value)} placeholder="Serial / licence number" className="w-full rounded border border-slate-600 bg-slate-950 p-3"/><select value={purchaseRef} onChange={e=>setPurchaseRef(e.target.value)} className="w-full rounded border border-slate-600 bg-slate-950 p-3"><option value="">Purchase reference (optional)</option>{purchases.map(p=><option key={p.reference} value={p.reference}>{p.reference} — {p.item}</option>)}</select><input value={location} onChange={e=>setLocation(e.target.value)} placeholder="Location" className="w-full rounded border border-slate-600 bg-slate-950 p-3"/><input list="asset-assignees" value={assignedTo} onChange={e=>setAssignedTo(e.target.value)} placeholder="Assigned to" className="w-full rounded border border-slate-600 bg-slate-950 p-3"/><datalist id="asset-assignees">{employees.map(e=><option key={e.name} value={e.name}/>)}</datalist><input type="date" value={warrantyUntil} onChange={e=>setWarrantyUntil(e.target.value)} className="w-full rounded border border-slate-600 bg-slate-950 p-3"/><select value={assetStatus} onChange={e=>setAssetStatus(e.target.value as typeof assetStatus)} className="w-full rounded border border-slate-600 bg-slate-950 p-3">{assetStatuses.map(s=><option key={s}>{s}</option>)}</select><button onClick={()=>save({kind:"asset",name:assetName,category:assetCategory,serialNo,purchaseRef,location,assignedTo,warrantyUntil,status:assetStatus,notes:""})} className="w-full rounded bg-cyan-600 p-3 font-bold">Save asset</button></div></section>
    </div>{message&&<p className="mt-4 text-sm text-cyan-200">{message}</p>}
    <section className="mt-6 rounded-xl border border-slate-700 bg-slate-900/70 p-6"><h2 className="text-xl font-bold">Operations registers</h2><div className="mt-4 grid gap-6 lg:grid-cols-3"><div><h3 className="font-bold">Vendors</h3>{vendors.length?vendors.slice(0,8).map(v=><p key={v.code} className="mt-2 text-sm">{v.name}<span className="text-slate-400"> · {v.category}</span></p>):<p className="mt-2 text-sm text-slate-400">No vendors added.</p>}</div><div><h3 className="font-bold">Purchases</h3>{purchases.length?purchases.slice(0,8).map(p=><p key={p.reference} className="mt-2 text-sm">{p.reference} · {p.item}<span className="text-slate-400"> · {p.status}</span></p>):<p className="mt-2 text-sm text-slate-400">No purchases added.</p>}</div><div><h3 className="font-bold">Assets</h3>{assets.length?assets.slice(0,8).map(a=><p key={a.assetId} className="mt-2 text-sm">{a.assetId} · {a.name}<span className="text-slate-400"> · {a.status}</span></p>):<p className="mt-2 text-sm text-slate-400">No assets added.</p>}</div></div></section>
  </main>;
}