"use client";
import { useRouter } from "next/navigation";
import { useState } from "react";

const statuses = ["New", "Scheduled", "In progress", "Waiting for customer", "Resolved", "Closed"] as const;
const priorities = ["Low", "Normal", "High", "Urgent"] as const;
type Status = typeof statuses[number];
type Priority = typeof priorities[number];
type Ticket = { row: number; reference: string; customer: string; workOrder: string; project: string; category: string; priority: Priority; location: string; request: string; assignee: string; scheduledDate: string; status: Status; resolution: string };
type WorkOrder = { reference: string; customer: string; projectName: string };
type Project = { name: string; client: string };

export function ServiceDeskWorkspace({ tickets, workOrders, projects }: { tickets: Ticket[]; workOrders: WorkOrder[]; projects: Project[] }) {
  const router = useRouter(); const today = new Date().toISOString().slice(0, 10);
  const [customer, setCustomer] = useState(""); const [workOrder, setWorkOrder] = useState(""); const [project, setProject] = useState("");
  const [category, setCategory] = useState("Technical support"); const [priority, setPriority] = useState<Priority>("Normal"); const [location, setLocation] = useState("");
  const [request, setRequest] = useState(""); const [assignee, setAssignee] = useState("Owner"); const [scheduledDate, setScheduledDate] = useState(today);
  const [status, setStatus] = useState<Status>("New"); const [notes, setNotes] = useState(""); const [message, setMessage] = useState("");
  const [updates, setUpdates] = useState<Record<number, { status: Status; resolution: string }>>(() => Object.fromEntries(tickets.map(ticket => [ticket.row, { status: ticket.status, resolution: ticket.resolution }])));
  function chooseWorkOrder(reference: string) { const item = workOrders.find(order => order.reference === reference); setWorkOrder(reference); if (item) { setCustomer(item.customer); setProject(item.projectName); } }
  async function save() { setMessage("Saving service ticket…"); const response = await fetch("/api/admin/service-tickets", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ customer, workOrder, project, category, priority, location, request, assignee, scheduledDate, status, notes }) }); const data = await response.json().catch(() => null) as { error?: string; reference?: string } | null; if (!response.ok) { setMessage(data?.error || "Could not save service ticket."); return; } setMessage("Ticket saved: " + data?.reference); router.refresh(); }
  async function update(ticket: Ticket) { const draft = updates[ticket.row]; const response = await fetch("/api/admin/service-tickets", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ row: ticket.row, status: draft.status, resolution: draft.resolution }) }); const data = await response.json().catch(() => null) as { error?: string } | null; setMessage(response.ok ? ticket.reference + " updated." : data?.error || "Could not update ticket."); if (response.ok) router.refresh(); }
  return <main className="mx-auto max-w-7xl p-8 text-slate-100"><p className="text-xs font-bold tracking-[.15em] text-cyan-300">SERVICE OPERATIONS</p><h1 className="mt-2 text-3xl font-black">Service Desk</h1><p className="mt-3 max-w-3xl text-slate-400">Log customer support, maintenance and field-service requests. Assign a person, schedule the visit and record the final resolution.</p>
    <section className="mt-6 rounded-xl border border-cyan-700/50 bg-cyan-950/20 p-5 text-sm text-cyan-100"><strong>Field visit control:</strong> record customer consent, site-safety requirements and the completed work in the ticket notes. Do not close a ticket until the resolution has been reviewed.</section>
    <section className="mt-6 rounded-xl border border-slate-700 bg-slate-900/70 p-6"><h2 className="text-xl font-bold">Create service ticket</h2><div className="mt-5 grid gap-4 md:grid-cols-2">
      <label>Linked work order<select value={workOrder} onChange={e => chooseWorkOrder(e.target.value)} className="mt-2 w-full rounded border border-slate-600 bg-slate-950 p-3"><option value="">Not linked / new request</option>{workOrders.map(item => <option key={item.reference} value={item.reference}>{item.reference} — {item.customer}</option>)}</select></label>
      <label>Customer *<input value={customer} onChange={e => setCustomer(e.target.value)} className="mt-2 w-full rounded border border-slate-600 bg-slate-950 p-3" /></label>
      <label>Project<select value={project} onChange={e => setProject(e.target.value)} className="mt-2 w-full rounded border border-slate-600 bg-slate-950 p-3"><option value="">No project selected</option>{projects.map(item => <option key={item.name + item.client} value={item.name}>{item.name} — {item.client}</option>)}</select></label>
      <label>Category *<input value={category} onChange={e => setCategory(e.target.value)} className="mt-2 w-full rounded border border-slate-600 bg-slate-950 p-3" placeholder="AMC, network, hardware, software…" /></label>
      <label>Priority<select value={priority} onChange={e => setPriority(e.target.value as Priority)} className="mt-2 w-full rounded border border-slate-600 bg-slate-950 p-3">{priorities.map(item => <option key={item}>{item}</option>)}</select></label>
      <label>Assigned person<input value={assignee} onChange={e => setAssignee(e.target.value)} className="mt-2 w-full rounded border border-slate-600 bg-slate-950 p-3" /></label>
      <label>Scheduled date *<input type="date" value={scheduledDate} onChange={e => setScheduledDate(e.target.value)} className="mt-2 w-full rounded border border-slate-600 bg-slate-950 p-3" /></label>
      <label>Status<select value={status} onChange={e => setStatus(e.target.value as Status)} className="mt-2 w-full rounded border border-slate-600 bg-slate-950 p-3">{statuses.map(item => <option key={item}>{item}</option>)}</select></label>
    </div><label className="mt-4 block">Site / location<input value={location} onChange={e => setLocation(e.target.value)} className="mt-2 w-full rounded border border-slate-600 bg-slate-950 p-3" /></label><label className="mt-4 block">Customer request *<textarea value={request} onChange={e => setRequest(e.target.value)} className="mt-2 min-h-24 w-full rounded border border-slate-600 bg-slate-950 p-3" placeholder="Issue, required service, equipment details…" /></label><label className="mt-4 block">Internal notes<textarea value={notes} onChange={e => setNotes(e.target.value)} className="mt-2 min-h-20 w-full rounded border border-slate-600 bg-slate-950 p-3" /></label><button type="button" onClick={save} className="mt-6 rounded-lg bg-cyan-600 px-5 py-3 font-bold">Save service ticket</button>{message && <p className="mt-3 text-sm text-cyan-200">{message}</p>}</section>
    <section className="mt-6 rounded-xl border border-slate-700 bg-slate-900/70 p-6"><h2 className="text-xl font-bold">Open and completed tickets</h2>{tickets.length ? <div className="mt-4 space-y-4">{tickets.map(ticket => { const draft = updates[ticket.row] || { status: ticket.status, resolution: ticket.resolution }; return <article key={ticket.row} className="rounded-lg border border-slate-700 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-bold">{ticket.reference} · {ticket.customer}</p><p className="mt-1 text-sm text-slate-400">{ticket.category} · {ticket.priority} · {ticket.scheduledDate} · {ticket.assignee || "Unassigned"}</p><p className="mt-2 text-sm">{ticket.request}</p></div><span className="rounded bg-slate-800 px-3 py-1 text-sm">{ticket.status}</span></div><div className="mt-4 grid gap-3 md:grid-cols-[220px_1fr_auto]"><select value={draft.status} onChange={e => setUpdates(old => ({ ...old, [ticket.row]: { ...draft, status: e.target.value as Status } }))} className="rounded border border-slate-600 bg-slate-950 p-3">{statuses.map(item => <option key={item}>{item}</option>)}</select><input value={draft.resolution} onChange={e => setUpdates(old => ({ ...old, [ticket.row]: { ...draft, resolution: e.target.value } }))} className="rounded border border-slate-600 bg-slate-950 p-3" placeholder="Resolution / visit report" /><button type="button" onClick={() => update(ticket)} className="rounded bg-slate-700 px-4 py-3 font-bold">Update</button></div></article>; })}</div> : <p className="mt-3 text-slate-400">No service tickets have been created yet.</p>}</section>
  </main>;
}